// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhpoUqe_lbXCTorhVw7e1_7UU0B29PuBU',
    appId: '1:1044784299707:web:3d4ad56a39e677572ef39e',
    messagingSenderId: '1044784299707',
    projectId: 'multiplayer-tic-tac-toe-app',
    authDomain: 'multiplayer-tic-tac-toe-app.firebaseapp.com',
    databaseURL: 'https://multiplayer-tic-tac-toe-app-default-rtdb.firebaseio.com',
    storageBucket: 'multiplayer-tic-tac-toe-app.firebasestorage.app',
    measurementId: 'G-C7KFXF7TCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPh8O565b-pPCFqm-mZjK1eUMjVajKHyw',
    appId: '1:1044784299707:android:b7e03c533a004b452ef39e',
    messagingSenderId: '1044784299707',
    projectId: 'multiplayer-tic-tac-toe-app',
    databaseURL: 'https://multiplayer-tic-tac-toe-app-default-rtdb.firebaseio.com',
    storageBucket: 'multiplayer-tic-tac-toe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyzQSk7Tkswbprrets_zGzcohOg4uk-Q',
    appId: '1:1044784299707:ios:c0ecea042bc20e542ef39e',
    messagingSenderId: '1044784299707',
    projectId: 'multiplayer-tic-tac-toe-app',
    databaseURL: 'https://multiplayer-tic-tac-toe-app-default-rtdb.firebaseio.com',
    storageBucket: 'multiplayer-tic-tac-toe-app.firebasestorage.app',
    iosClientId: '1044784299707-vsclrd2vtpeii1m9ca8fpl4n451epvk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayerTicTacToeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGyzQSk7Tkswbprrets_zGzcohOg4uk-Q',
    appId: '1:1044784299707:ios:c0ecea042bc20e542ef39e',
    messagingSenderId: '1044784299707',
    projectId: 'multiplayer-tic-tac-toe-app',
    databaseURL: 'https://multiplayer-tic-tac-toe-app-default-rtdb.firebaseio.com',
    storageBucket: 'multiplayer-tic-tac-toe-app.firebasestorage.app',
    iosClientId: '1044784299707-vsclrd2vtpeii1m9ca8fpl4n451epvk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayerTicTacToeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhpoUqe_lbXCTorhVw7e1_7UU0B29PuBU',
    appId: '1:1044784299707:web:9d40e1c8cf991fde2ef39e',
    messagingSenderId: '1044784299707',
    projectId: 'multiplayer-tic-tac-toe-app',
    authDomain: 'multiplayer-tic-tac-toe-app.firebaseapp.com',
    databaseURL: 'https://multiplayer-tic-tac-toe-app-default-rtdb.firebaseio.com',
    storageBucket: 'multiplayer-tic-tac-toe-app.firebasestorage.app',
    measurementId: 'G-BDY9ELHDGH',
  );

}